update GH Action versions
SeisoLLC/cookiecutter-python pull request #116
Opened 2024-06-05 20:24 UTC by seanctech

# Contributor Comments

## Pull Request Checklist

Thank you for submitting a contribution to cookiecutter-python!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [x] If you are adding a dependency, please explain how it was chosen.
- [x] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results.
- [x] Validate that documentation is accurate and aligned to any project updates or additions.

Don't forget our more detailed contribution guidelines
[here](https://github.com/SeisoLLC/operations/blob/main/documents/software-guidelines.md#contributing-to-a-repository).

2024-06-06 11:09 UTC, JonZeolla requested changes

2024-06-06 11:09 UTC, JonZeolla commented on {{cookiecutter.project_name|replace(" ", "")}}/.github/workflows/commit.yml
> +        run: task -v test -- debug
Do we want to keep this on or was it just temporary

2024-06-06 11:09 UTC, JonZeolla commented on {{cookiecutter.project_name|replace(" ", "")}}/.github/workflows/commit.yml
> +        uses: arduino/setup-task@v3
I don't think v3 exists

2024-06-06 11:09 UTC, JonZeolla commented on {{cookiecutter.project_name|replace(" ", "")}}/.github/workflows/release.yml
> +          name: Vulns-${{ "{{ eng.SANITITZED_PLATFORM }}" }}
Typo - eng should be env and sanitized is spelt wrong

2024-06-21 19:37 UTC, ChiefHolland approved these changes
LGTM

2024-09-04 21:32 UTC, JonZeolla approved these changes

2024-09-04 21:32 UTC, merged